### PR TITLE
fix translation for Laravel 6

### PR DESCRIPTION
**Pull request by sinetix**

### CODE REVIEW

**Comment by sinetix** [comment]
Laravel 6 upgrade

**Review by sinetix — COMMENTED** [review]
In Laravel 6, the Lang::trans and Lang::transChoice methods of the translator have been renamed to Lang::get and Lang::choice.

https://laravel.com/docs/6.x/upgrade#trans-and-trans-choice

**Comment by TheoKouzelis** [comment]
Hi @sinetix 

Thanks for you PR. I will review this tonight.

**Comment by marcaparent** [comment]
@TheoKouzelis Any news on this? I'd need it in my project 🙏

**Comment by TheoKouzelis** [comment]
Hi @marcaparent and @sinetix 

I've added this in with this https://github.com/TheoKouzelis/laravel-mailgun-email-validation/pull/8 which supports both ways of getting the translation. 

Thanks for the PR.

**Pull request closed without merging**
